stages:
  - check
  - deploy

flake8:
  stage: check
  image: git.internal.com:4567/namespace/dockerfiles-repo/flake8-py36
  script:
    - echo "PASS"
    # flake8 mrproper/

deploy-mrchecker:
  stage: deploy
  image: artifact.internal.com:6555/docker:latest
  variables:
    # TODO: Set the correct host before real deployment - currently wtl-ldocker-2
    DOCKER_HOST: ssh://docker@10.X.X.X
  script:
    - |
      echo "https://artifact.internal.com/artifactory/alpine/v3.20/main" > /etc/apk/repositories
      echo "https://artifact.internal.com/artifactory/alpine/v3.20/community" >> /etc/apk/repositories
      wget "http://artifact.internal.com/artifactory/api/security/keypair/public/repositories/alpine" \
        -O /etc/apk/keys/apline-rsa.rsa.pub
      apk add python3 python3-dev openssh-client
    # SSH setup (update host/key as needed before prod)
    - mkdir -p ~/.ssh
    - python3 -c 'import os, base64; print(base64.decodebytes(os.getenv("LDOCKER_SSH_KEY").encode("utf-8")).decode("utf-8"))' >~/.ssh/id_rsa
    - ssh-keyscan 10.X.X.X > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/*
    # Docker info & build
    - docker version
    - docker build -t mr-checker-vp-test mrproper && echo "Docker build completed"

deploy-webhook:
  stage: deploy
  image: artifact.internal.com:6555/docker:latest
  variables:
    # TODO: Set the correct host before real deployment - currently wtl-ldocker-2
    DOCKER_HOST: ssh://docker@10.X.X.X
    ENV_FILE_PATH: "/tmp"
  script:
    - |
      echo "https://artifact.internal.com/artifactory/alpine/v3.20/main" > /etc/apk/repositories
      echo "https://artifact.internal.com/artifactory/alpine/v3.20/community" >> /etc/apk/repositories
      wget "http://artifact.internal.com/artifactory/api/security/keypair/public/repositories/alpine" \
        -O /etc/apk/keys/apline-rsa.rsa.pub
      apk add python3 python3-dev openssh-client
    # SSH setup (update host/key as needed before prod)
    - mkdir -p ~/.ssh
    - python3 -c 'import os, base64; print(base64.decodebytes(os.getenv("LDOCKER_SSH_KEY").encode("utf-8")).decode("utf-8"))' >~/.ssh/id_rsa
    - ssh-keyscan 10.X.X.X > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/*
    # Docker info & build
    - docker version
    - docker build -t mrproper-webhook-vp-test webhook-server && echo "Docker build completed"
    # Stop and remove any running container with this name (if exists)
    - |
      if docker ps -a --format '{{.Names}}' | grep -Eq '^mrproper-webhook-vp-test$'; then
        docker stop mrproper-webhook-vp-test || echo "No running container to stop"
        docker rm mrproper-webhook-vp-test || echo "No container to remove"
      fi
    # Create mrproper.env file in configurable location (default: /tmp)
    - |
      ssh docker@10.X.X.X "cat > ${ENV_FILE_PATH}/mrproper.env << 'EOF'
      GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
      EOF"
      echo "Created mrproper.env in: ${ENV_FILE_PATH}"
    # Create log directories on host
    - |
      ssh docker@10.X.X.X "mkdir -p /home/docker/tmp/mr-validator-logs && chmod 755 /home/docker/tmp/mr-validator-logs"
      echo "Created log directory: /home/docker/tmp/mr-validator-logs"
    # Run the new container with debugging
    - |
      docker run -d --name mrproper-webhook-vp-test \
        --restart=unless-stopped \
        --publish 9912:9912 \
        -t \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume "${ENV_FILE_PATH}/mrproper.env:/mrproper.env" \
        --volume "/tmp:/tmp" \
        --volume "/home/docker/tmp/mr-validator-logs:/home/docker/tmp/mr-validator-logs" \
        mrproper-webhook-vp-test \
        python3 /srv/server.py
    # Wait a moment and check if container started successfully
    - sleep 3
    - |
      if docker ps | grep -q mrproper-webhook-vp-test; then
        echo "Container started successfully"
        docker logs mrproper-webhook-vp-test
      else
        echo "Container failed to start"
        docker logs mrproper-webhook-vp-test
        exit 1
      fi
